# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: biometrica
services:
  app:
    image: biometrica
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/Biometrica
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI=http://keycloak:9080/realms/jhipster
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID=web_app
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET=web_app
      - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka:9092
      - JAVA_OPTS=-Djgroups.tcp.address=NON_LOOPBACK
        -Djava.net.preferIPv4Stack=true
    ports:
      - 127.0.0.1:8087:8087
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8087/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      mongodb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
  mongodb:
    extends:
      file: ./mongodb.yml
      service: mongodb
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
  kafka:
    extends:
      file: ./kafka.yml
      service: kafka
  zookeeper:
    extends:
      file: ./kafka.yml
      service: zookeeper
